package com.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greendao.db.Question;
import com.greendao.db.UserResponses;

import com.greendao.db.QuestionDao;
import com.greendao.db.UserResponsesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig userResponsesDaoConfig;

    private final QuestionDao questionDao;
    private final UserResponsesDao userResponsesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        userResponsesDaoConfig = daoConfigMap.get(UserResponsesDao.class).clone();
        userResponsesDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        userResponsesDao = new UserResponsesDao(userResponsesDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(UserResponses.class, userResponsesDao);
    }
    
    public void clear() {
        questionDaoConfig.getIdentityScope().clear();
        userResponsesDaoConfig.getIdentityScope().clear();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public UserResponsesDao getUserResponsesDao() {
        return userResponsesDao;
    }

}
