package com.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.greendao.db.Question;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUESTION".
*/
public class QuestionDao extends AbstractDao<Question, Long> {

    public static final String TABLENAME = "QUESTION";

    /**
     * Properties of entity Question.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Q_no = new Property(1, Integer.class, "q_no", false, "Q_NO");
        public final static Property Q_code = new Property(2, String.class, "q_code", false, "Q_CODE");
        public final static Property Exam_code = new Property(3, String.class, "exam_code", false, "EXAM_CODE");
        public final static Property Max_marks = new Property(4, String.class, "max_marks", false, "MAX_MARKS");
        public final static Property Question = new Property(5, String.class, "question", false, "QUESTION");
        public final static Property Image = new Property(6, String.class, "image", false, "IMAGE");
        public final static Property Option_json = new Property(7, String.class, "option_json", false, "OPTION_JSON");
        public final static Property Answer = new Property(8, String.class, "answer", false, "ANSWER");
    };

    private DaoSession daoSession;


    public QuestionDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUESTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"Q_NO\" INTEGER UNIQUE ," + // 1: q_no
                "\"Q_CODE\" TEXT," + // 2: q_code
                "\"EXAM_CODE\" TEXT," + // 3: exam_code
                "\"MAX_MARKS\" TEXT," + // 4: max_marks
                "\"QUESTION\" TEXT," + // 5: question
                "\"IMAGE\" TEXT," + // 6: image
                "\"OPTION_JSON\" TEXT," + // 7: option_json
                "\"ANSWER\" TEXT);"); // 8: answer
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUESTION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Question entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer q_no = entity.getQ_no();
        if (q_no != null) {
            stmt.bindLong(2, q_no);
        }
 
        String q_code = entity.getQ_code();
        if (q_code != null) {
            stmt.bindString(3, q_code);
        }
 
        String exam_code = entity.getExam_code();
        if (exam_code != null) {
            stmt.bindString(4, exam_code);
        }
 
        String max_marks = entity.getMax_marks();
        if (max_marks != null) {
            stmt.bindString(5, max_marks);
        }
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(6, question);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(7, image);
        }
 
        String option_json = entity.getOption_json();
        if (option_json != null) {
            stmt.bindString(8, option_json);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(9, answer);
        }
    }

    @Override
    protected void attachEntity(Question entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Question readEntity(Cursor cursor, int offset) {
        Question entity = new Question( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // q_no
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // q_code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // exam_code
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // max_marks
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // question
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // image
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // option_json
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // answer
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Question entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQ_no(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setQ_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExam_code(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMax_marks(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQuestion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImage(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOption_json(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAnswer(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Question entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Question entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
