package com.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER_RESPONSES".
 */
public class UserResponses {

    private Long id;
    private Integer q_no;
    private String q_code;
    private String exam_code;
    private String max_marks;
    private String question;
    private String answer;
    private String user_response;
    private long userId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserResponses() {
    }

    public UserResponses(Long id) {
        this.id = id;
    }

    public UserResponses(Long id, Integer q_no, String q_code, String exam_code, String max_marks, String question, String answer, String user_response, long userId) {
        this.id = id;
        this.q_no = q_no;
        this.q_code = q_code;
        this.exam_code = exam_code;
        this.max_marks = max_marks;
        this.question = question;
        this.answer = answer;
        this.user_response = user_response;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQ_no() {
        return q_no;
    }

    public void setQ_no(Integer q_no) {
        this.q_no = q_no;
    }

    public String getQ_code() {
        return q_code;
    }

    public void setQ_code(String q_code) {
        this.q_code = q_code;
    }

    public String getExam_code() {
        return exam_code;
    }

    public void setExam_code(String exam_code) {
        this.exam_code = exam_code;
    }

    public String getMax_marks() {
        return max_marks;
    }

    public void setMax_marks(String max_marks) {
        this.max_marks = max_marks;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getUser_response() {
        return user_response;
    }

    public void setUser_response(String user_response) {
        this.user_response = user_response;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
